options:
  max-time: 10
  docker: true

clone:
  depth: 3

pipelines:
  default:
  - step:
      name: test
      image: egymgmbh/golang:latest
      script:
      # prepare environment
      - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
      - mkdir -pv "${PACKAGE_PATH}"
      - tar -cO --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
      - cd "${PACKAGE_PATH}"
      # run tests
      - golint   -set_exit_status $(go list ./... | grep -v /vendor/)
      - go vet   -v               $(go list ./... | grep -v /vendor/)
      - go build -v               $(go list ./... | grep -v /vendor/)
      - |
        echo "" > coverage.txt
        for d in $(go list ./... | grep -v /vendor/); do
            go test -v -race -coverprofile=profile.out -covermode=atomic $d
            if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
            fi
        done
      - bash <(curl -s https://codecov.io/bash)