options:
  max-time: 10
  docker: true

clone:
  depth: 3

pipelines:
  default:
  - step:
      name: test
      image: golang:latest
      script:
      # prepare environment
      - go get github.com/golang/lint/golint
      - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
      - mkdir -pv "${PACKAGE_PATH}"
      - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
      - cd "${PACKAGE_PATH}"
      # run tests
      - golint   -set_exit_status $(go list ./... | grep -v /vendor/)
      - go vet   -v               $(go list ./... | grep -v /vendor/)
      - go build -v               $(go list ./... | grep -v /vendor/)
      - go test  -v -race         $(go list ./... | grep -v /vendor/)
